# Site Settings
title: "Insight Ingenious Documentation"
description: >-
  Comprehensive documentation for Insight Ingenious - A powerful conversation workflow framework for building AI-powered applications with Azure OpenAI.
# Repository information
repository: "Insight-Services-APAC/ingenious"
baseurl: "/ingenious"
url: "https://insight-services-apac.github.io"
# Theme
remote_theme: "mmistakes/minimal-mistakes@4.27.1"
# Build settings
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false
# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
# Enable Mermaid.js support
mermaid: true
# Author
author:
  name: "Insight Services APAC"
  bio: "Enterprise AI Solutions"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Insight-Services-APAC"
# Site Footer
footer:
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/Insight-Services-APAC/ingenious"
# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: false
      share: true
      related: true
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: false
      sidebar:
        nav: "docs"
# Collections
collections:
  docs:
    output: true
    permalink: /:collection/:name/
# Navigation
navigation:
  - title: "Quick Start"
    url: /getting-started/
  - title: "Guides"
    url: /guides/
  - title: "API Reference"
    url: /api/
  - title: "Architecture"
    url: /architecture/
  - title: "Development"
    url: /development/
# Exclude from processing
exclude:
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
# Reading Files
include:
  - .htaccess
  - _pages
# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed
# Outputting
permalink: /:categories/:title/
paginate: 5
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
# HTML Compression
compress_html:
  clippings: all
  ignore:
    envs: development
# Archives
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# SEO Related
google_site_verification:
bing_site_verification:
alexa_site_verification:
yandex_site_verification:
naver_site_verification:
# Social Sharing
twitter:
  username:
facebook:
  username:
  app_id:
  publisher:
social:
  type: Organization
  name: Insight Services APAC
  links:
    - "https://github.com/Insight-Services-APAC"
# Analytics
analytics:
  provider: false
# Search
search: true
search_full_content: true
search_provider: lunr
# Mermaid.js Configuration
after_footer_scripts:
  - https://cdn.jsdelivr.net/npm/mermaid@11/dist/mermaid.min.js
  - /assets/js/mermaid-init.js
